---
calculate:
  from:
    days: 7
  timeframe: 15
  min_prices: 400
  max_set_size_diff_pct: 90
  overlap_pct: 90
  max_p_value: 0.05
monitor:
  from:
    minutes: 10
  interval: 10
  min_prices: 400
  max_set_size_diff_pct: 50
  overlap_pct: 50
  max_p_value: 0.05
  divergence_threshold: 0.8
...